name: 'Keeper Secrets Manager Config Provision GitHub Action'
description: 'A GitHub Action to create Keeper Secrets Manager Config as a GitHub Secret from Keeper Secrets Manager One Time Token'
author: 'Keeper Security Inc. <sm@keepersecurity.com>'
inputs:
  accessToken:
    required: true
    description: Personal access token with permission to modify repository or organization secrets
  oneTimeToken:
    required: true
    description: Keeper Secrets Manager One Time Token
  configName:
    required: true
    description: Name of the GitHub Secret that will hold the Keeper Secrets Manager Config
runs:
  using: 'node12'
  main: 'dist/index.js'
